<wsdl:definitions	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
					xmlns:tns="http://spotify.com/services/MusicService/wsdl/"
					xmlns:wsdl="http://spotify.com/services/MusicService/wsdl/"
					xmlns:xs="http://www.w3.org/2001/XMLSchema"
					xmlns="https://www.w3schools.com"
					name="MusicService"
					targetNamespace="http://spotify.com/services/MusicService/wsdl/">
					
	<!--WSDL TYPES-->
	<wsdl:types>
		<xs:schema>
			<xs:import namespace="http://spotify.com/services/music/xsd/" schemaLocation="MusicService.xsd"/>
		</xs:schema>
	</wsdl:types>
	
	<!--WSDL MESSAGE-->
	<!--Reuse Message Output-->
	<wsdl:message name="GetMusicOutput">
		<wsdl:part name="music" type="tns:MusicOutput"/>
	</wsdl:message>
	
	<wsdl:message name="GetMusicListOutput">
		<wsdl:part name="musicList" type="tns:MusicListOutput"/>
	</wsdl:message>
	
	<!--OP1 PlayMusic-->
		<!--Input-->
	<wsdl:message name="GetPlayMusicInput">
		<wsdl:part name="playMusic" type="tns:playMusicInput"/>
	</wsdl:message>
		<!--Output-->
			<!--In reuse message output name is "GetMusicOutput"-->
	
	<!--OP2 StopMusic-->
		<!--Input-->
	<wsdl:message name="GetStopMusicInput">
		<wsdl:part name="stopMusic" type="tns:stopMusicInput"/>
	</wsdl:message>
		<!--Output-->
			<!--In reuse message output name is "GetMusicOutput"-->
		
	<!--OP3 NextMusicFreePlan-->
		<!--Input-->
	<wsdl:message name="GetNextMusicFreePlanInput">
		<wsdl:part name="nextMusicFreePlan" type="tns:nextMusicFreePlanInput"/>
	</wsdl:message>
		<!--Output-->
			<!--In reuse message output name is "GetMusicOutput"-->
		
	<!--OP4 NextMusicPremiumPlan-->
		<!--Input-->
	<wsdl:message name="GetNextMusicPremiumPlanInput">
		<wsdl:part name="nextMusicPremiumPlan" type="tns:nextMusicPremiumPlanInput"/>
	</wsdl:message>
		<!--Output-->
			<!--In reuse message output name is "GetMusicOutput"-->
		
	<!--OP5 StartLoopMusic-->
		<!--Input-->
	<wsdl:message name="GetStartLoopMusicInput">
		<wsdl:part name="startLoopMusic" type="tns:startLoopMusicInput"/>
	</wsdl:message>
	
	<!--OP6 StopLoopMusic-->
		<!--Input-->
	<wsdl:message name="GetStopLoopMusicInput">
		<wsdl:part name="stopLoopMusic" type="tns:stopLoopMusicInput"/>
	</wsdl:message>
	
	<!--OP7 RandomMusic-->
		<!--Output-->
			<!--In reuse message output name is "GetMusicListOutput"-->

	<!--OP8 StartShuffleMusic-->
		<!--Input-->
	<wsdl:message name="GetStartShuffleMusicInput">
		<wsdl:part name="startShuffleMusic" type="tns:startShuffleMusicInput"/>
	</wsdl:message>
	
	<!--OP9 StopShuffleMusic-->
		<!--Input-->
	<wsdl:message name="GetStopShuffleMusicInput">
		<wsdl:part name="stopShuffleMusic" type="tns:stopShuffleMusicInput"/>
	</wsdl:message>
	
	<!--OP10 ShowMusicList-->
		<!--Output-->
			<!--In reuse message output name is "GetMusicListOutput"-->
			
	<!--OP11 ShareMusic-->
		<!--Output-->
	<wsdl:message name="GetShareMusicOutput">
		<wsdl:part name="shareMusic" type="tns:shareMusicOutput"/>
	</wsdl:message>
	
	<!--OP12 ShowMusicDetail-->
		<!--Output-->
	<wsdl:message name="GetShowMusicDetailOutput">
		<wsdl:part name="showMusicDetail" type="tns:showMusicDetailOutput"/>
	</wsdl:message>
	
	<!--WSDL PORTTYPE-->
	<wsdl:portType name="MusicService">
		<wsdl:operation name="PlayMusic">
			<wsdl:input message="tns:GetPlayMusicInput"/>
			<wsdl:output message="tns:GetMusicOutput"/>
		</wsdl:operation>
		<wsdl:operation name="StopMusic">
			<wsdl:input message="tns:GetStopMusicInput"/>
			<wsdl:output message="tns:GetMusicOutput"/>
		</wsdl:operation>
		<wsdl:operation name="NextMusicFreePlan">
			<wsdl:input message="tns:GetNextMusicFreePlanInput"/>
			<wsdl:output message="tns:GetMusicOutput"/>
		</wsdl:operation>
		<wsdl:operation name="NextMusicPremiumPlan">
			<wsdl:input message="tns:GetNextMusicPremiumPlanInput"/>
			<wsdl:output message="tns:GetMusicOutput"/>
		</wsdl:operation>
		<wsdl:operation name="StartLoopMusic">
			<wsdl:input message="tns:GetStartLoopMusicInput"/>
		</wsdl:operation>
		<wsdl:operation name="StopLoopMusic">
			<wsdl:input message="tns:GetStopLoopMusicInput"/>
		</wsdl:operation>
		<wsdl:operation name="RandomMusic">
			<wsdl:output message="tns:GetMusicListOutput"/>
		</wsdl:operation>
		<wsdl:operation name="StartShuffleMusic">
			<wsdl:input message="tns:GetStartShuffleMusicInput"/>
		</wsdl:operation>
		<wsdl:operation name="StopShuffleMusic">
			<wsdl:input message="tns:GetStopShuffleMusicInput"/>
		</wsdl:operation>
		<wsdl:operation name="ShowMusicList">
			<wsdl:output message="tns:GetMusicListOutput"/>
		</wsdl:operation>
		<wsdl:operation name="ShareMusic">
			<wsdl:output message="tns:GetShareMusicOutput"/>
		</wsdl:operation>
		<wsdl:operation name="ShowMusicDetail">
			<wsdl:output message="tns:GetShowMusicDetailOutput"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<!--WSDL BINDING-->
	<wsdl:binding name="MusicServiceSoapBinding" type="tns:MusicService">
		<soap:binding style="document" transport="https://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="PlayMusic">
			<soap:operation soapAction="http://spotify.com/services/MusicService/"/>
			<wsdl:input>
				 <soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				 <soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="StopMusic">
			<soap:operation soapAction="http://spotify.com/services/MusicService/StopMusic/"/>
			<wsdl:input>
				 <soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				 <soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="NextMusicFreePlan">
			<soap:operation soapAction="http://spotify.com/services/MusicService/NextMusicFreePlan/"/>
			<wsdl:input>
				 <soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				 <soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="NextMusicPremiumPlan">
			<soap:operation soapAction="http://spotify.com/services/MusicService/NextMusicPremiumPlan/"/>
			<wsdl:input>
				 <soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				 <soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="StartLoopMusic">
			<soap:operation soapAction="http://spotify.com/services/MusicService/StartLoopMusic/"/>
			<wsdl:input>
				 <soap:body use="literal"/>
			</wsdl:input>
		</wsdl:operation>
		<wsdl:operation name="StopLoopMusic">
			<soap:operation soapAction="http://spotify.com/services/MusicService/StopLoopMusic/"/>
			<wsdl:input>
				 <soap:body use="literal"/>
			</wsdl:input>
		</wsdl:operation>
		<wsdl:operation name="RandomMusic">
			<soap:operation soapAction="http://spotify.com/services/MusicService/RandomMusic/"/>
			<wsdl:output>
				 <soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="StartShuffleMusic">
			<soap:operation soapAction="http://spotify.com/services/MusicService/StartShuffleMusic/"/>
			<wsdl:input>
				 <soap:body use="literal"/>
			</wsdl:input>
		</wsdl:operation>
		<wsdl:operation name="StopShuffleMusic">
			<soap:operation soapAction="http://spotify.com/services/MusicService/StopShuffleMusic/"/>
			<wsdl:input>
				 <soap:body use="literal"/>
			</wsdl:input>
		</wsdl:operation>
		<wsdl:operation name="ShowMusicList">
			<soap:operation soapAction="http://spotify.com/services/MusicService/ShowMusicList/"/>
			<wsdl:output>
				 <soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="ShareMusic">
			<soap:operation soapAction="http://spotify.com/services/MusicService/ShareMusic/"/>
			<wsdl:output>
				 <soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="ShowMusicDetail">
			<soap:operation soapAction="http://spotify.com/services/MusicService/ShowMusicDetail/"/>
			<wsdl:output>
				 <soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<!--WSDL SERVICE-->
	<wsdl:service name="MusicService">
		<wsdl:documentation>Music Service</wsdl:documentation>
		<wsdl:port name="MusicServicePort" binding="tns:MusicServiceSoapBinding">
			<soap:address location="http://spotify.com/services/MusicService/"/>
		</wsdl:port>
	</wsdl:service>
	
</wsdl:definitions>